create database aula_cursores;
use aula_cursores;

CREATE TABLE VENDEDORES(
IDVENDEDOR INT PRIMARY KEY auto_increment,
NOME varchar(30),
JAN INT,
FEV INT,
MAR INT
);

INSERT INTO VENDEDORES value(NULL, 'MAFRA', 32432, 478596,74854);
INSERT INTO VENDEDORES value(NULL, 'CLARA', 72545, 412,512768);
INSERT INTO VENDEDORES value(NULL, 'JOÃO', 452452, 4546,1625);
INSERT INTO VENDEDORES value(NULL, 'LILIAN', 341, 4776,74754);
INSERT INTO VENDEDORES value(NULL, 'ANTONIO', 47477, 45526,4527);
INSERT INTO VENDEDORES value(NULL, 'GLORIA', 86455, 125125,45215);

SELECT * FROM VENDEDORES;

SELECT NOME, (JAN + FEV + MAR) AS TOTAL FROM VENDEDORES;

SELECT NOME, (JAN + FEV + MAR) AS TOTAL ,(JAN + FEV + MAR)/3 AS MÉDIA FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
	NOME varchar(50),
	JAN INT,
	FEV INT,
	MAR INT,
    TOTAL INT,
    MEDIA INT
);



CREATE PROCEDURE INSERE_DADOS()
BEGIN
	DECLARE FIM INT DEFAULT 0;
    DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
    DECLARE VNOME VARCHAR(50);
    
    DECLARE REG CURSOR FOR(
		SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
        
    );
    
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM=1;
    OPEN REG;
    
    REPEAT
    
		FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
        IF NOT FIM THEN 
			SET VTOTAL = VAR1 + VAR2 + VAR3;
            SET VMEDIA = VTOTAL/3;
            
            INSERT INTO VEND_TOTAL VALUES(VNOME, VAR1, VAR2, VAR3, VTOTAL, VMEDIA);
		END IF;
	UNTIL FIM END REPEAT;
    CLOSE REG;
END
$

DELIMITER ;

SELECT * FROM VENDEDORES;
SELECT * FROM VEND_TOTAL;

CALL INSERE_DADOS();


