CREATE DATABASE AULA_AUTORELACIONAMENTO;

USE AULA_AUTORELACIONAMENTO;
create table CURSOS(
IDCURSO INT PRIMARY KEY auto_increment,
NOME VARCHAR(30),
HORAS INT,
VALOR FLOAT(10,2),
ID_PREREQ INT
);

ALTER TABLE CURSOS ADD constraint FK_PREREQ
foreign key(ID_PREREQ) REFERENCES CURSOS(IDCURSO);

INSERT INTO CURSOS VALUES(NULL, 'BD RELACIONAL', 20, 400.00, NULL);
INSERT INTO CURSOS VALUES(NULL, 'BUSINESS INTELIGENCE', 40, 800.00, 1);
INSERT INTO CURSOS VALUES(NULL, 'RELATÓRIOS AVANÇADOS', 20, 600.00, 2);
INSERT INTO CURSOS VALUES(NULL, 'LÓGICA DE PROGRAMAÇÃO', 20, 400.00, NULL);
INSERT INTO CURSOS VALUES(NULL, 'RUBY', 30, 500.00, 4);

SELECT * FROM CURSOS;

SELECT NOME, VALOR, HORAS, IFNULL(ID_PREREQ, "SEM REQ") REQUISITO
FROM CURSOS;

SELECT C.NOME AS CURSO, C.VALOR AS VALOR, C.HORAS AS CARGA_HORÁRIA, 
	   IFNULL(P.NOME, "---") AS PREREQ
FROM CURSOS C
LEFT JOIN CURSOS P 
ON P.IDCURSO = C.ID_PREREQ;
-- tras todos os cursos, inclusive os que não tem pré requisito


